config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:create, :destroy]
  resources :products
  root to: 'pages#home'
  get '/contact', to: 'messages#new', as: :contact
  get '/admin', to: 'pages#admin'

  get '/buy/:id', to: 'transactions#new', as: :show_buy
  post '/buy/:id', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup
  get '/download/:guid', to: 'transactions#download', as: :download
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  validates_numericality_of :price, greater_than: 0.49, message: 'must be at least 50 cents'

  has_many :sales

  scope :latest, -> { last(4).reverse }
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product, counter_cache: true
  before_create :populate_guid

  private

  def populate_guid
    self.guid = SecureRandom.uuid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'secret', only: :destroy
  before_action :set_message, only: :destroy

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    redirect_to contact_path if @message.save
  end

  def destroy
    redirect_to admin_path if @message.delete
  end

  private

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'secret', only: :admin

  def home
    @latest = Product.latest
  end

  def admin
    @products = Product.all
    @messages = Message.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'secret', except: [:index, :show]
  before_action :set_product, except: [:index, :create, :new]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      format.html { redirect_to product_path @product, notice: 'Product was successfully created.' } if @product.save
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_path @product, notice: 'Product was successfully updated.' }
      end
    end
  end

  def destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Product was successfully deleted.' } if @product.destroy
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :asset_url)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @product = @sale.product
  end

  def create
    product = Product.find(params[:id])
    token = params[:stripeToken]

    begin
      Stripe::Charge.create(amount: (product.price * 100).to_i, currency: 'usd', card: token, description: params[:email])
      @sale = product.sales.create!(email: params[:email])
      redirect_to pickup_url(guid: @sale.guid)
    rescue Stripe::CardError => e
      @error = e
      render :new
    end
  end

  def download
    @sale = Sale.find_by!(guid: params[:guid])
    redirect_to @sale.product.asset_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <p>Codeplace Store &copy; <%= Time.now.year %></p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Codeplace Store', root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Products', products_path %>
        </li>
        <li>
          <%= link_to 'Contact', contact_path %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeplace Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->
    <%= render 'layouts/navbar' %>

    <!-- Page Content -->
    <div class="container">
      <%= yield %>
      <hr>

      <!-- Footer -->
      <%= render 'layouts/footer' %>
    </div>
    <!-- /.container -->
  </body>
</html>

app/views/messages/new.html.erb
<!-- Title -->
<div class="row">
    <div class="col-lg-12">
        <h3>Contact</h3>
    </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p>Have a question or want further information?</p>
    <p>Fill in the short form and we will get back to you as soon as possible.</p>
    <br>
    <!-- BEGIN CONTACT PANEL -->
    <div class="panel panel-default well">
      <div class="panel-body">
        <%= simple_form_for @message, url: messages_path do |f| %>
          <div class="form-group">
              <div class="col-sm-12">
                  <div class="input-group">
                      <div class="input-group-addon">
                          <i class="fa fa-user"></i>
                      </div>
                      <%= f.input :name, placeholder: 'Enter name', input_html: { class: 'form-control' }, label: false %>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-12">
                  <div class="input-group">
                      <div class="input-group-addon">
                          <i class="fa fa-envelope"></i>
                      </div>
                      <%= f.input :email, placeholder: 'Enter email', input_html: { class: 'form-control' }, label: false %>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-12">
                  <div class="input-group">
                      <div class="input-group-addon">
                          <i class="fa fa-comment fa-2"></i>
                      </div>
                      <%= f.input :body, placeholder: 'Enter your message here', input_html: { class: 'form-control', rows: '5' }, label: false %>
                  </div>
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-12">
                <%= f.button :submit, 'Send', class: 'btn btn-default btn-info' %>
                <%= link_to 'Back', products_path, class: 'btn btn-default' %>
              </div>
          </div>
        <% end %>
      </div>
      <!-- end panel-body -->
    </div>
    <!-- end panel -->
    <!-- END CONTACT PANEL -->
  </div>
  <!-- end col-md-8 -->
</div>
<!-- /.row -->
<div class="row">
  <div class="col-md-12">
  </div>
</div>
<!-- /.row -->

app/views/pages/admin.html.erb
<div class="row">
  <div class="col-sm-3 col-md-2 sidebar">
  <h4 class="page-header">Overview</h4>
    <ul class="nav nav-sidebar">
      <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
    </ul>
  </div>
  <div class="col-sm-9 col-md-10 main">
    <h4 class="page-header">Products (<%= link_to 'New product', new_product_path %>)</h4>
    <div class="row table-products">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Title</th>
              <th>Price</th>
              <th>Sales Count</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= product.title %></td>
                <td><%= number_to_currency(product.price) %></td>
                <td><%= product.sales_count %></td>
                <td>
                  <%= link_to product_path(product) do %><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;<% end %>
                  <%= link_to edit_product_path(product) do %><i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;<% end %>
                  <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-times" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <h4 class="page-header">Messages</h4>
    <div class="row table-messages">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Message</th>
              <th>Sent</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @messages.each do |message| %>
              <tr>
                <td><%= message.name %></td>
                <td><%= message.email %></td>
                <td><%= message.body %></td>
                <td><%= time_ago_in_words(message.created_at) %></td>
                <td>
                  <%= link_to message, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-times" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!-- Jumbotron Header -->
 <header class="jumbotron unspacer">
   <h1>Welcome to the Codeplace Store</h1>
   <p>Our awesome store is just one click away.</p>
   <p><%= link_to 'See Products', products_path, class: 'btn btn-primary btn-large' %>
   </p>
 </header>

 <hr>

<!-- Title -->
<div class="row unspacer">
    <div class="col-lg-12">
        <h3>Latest from our store</h3>
    </div>
</div>
<!-- /.row -->

<!-- Page Features -->
<div class="row text-center">
  <% @latest.each do |product| %>
  <div class="col-md-3 col-sm-6 feature">
    <div class="thumbnail">
      <img src="http://placehold.it/800x500" class="img-responsive">
      <div class="caption">
        <h3><%= product.title %></h3>
        <p><%= product.description %></p>
        <p>
          <%= link_to 'More', product_path(product), class: "btn btn-default" %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>
<!-- /.row -->

app/views/products/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="col-md-8">
        <img src="http://placehold.it/800x500" class="img-responsive" />
      </div>
      <div class="col-md-4">
        <%= simple_form_for(@product, html: { class: 'form-horizontal' }) do |f| %>
          <%= f.input :title, placeholder: "Title" %>
          <%= f.input :description, placeholder: "Description" %>
          <%= f.input :price %>
          <%= f.input :asset_url, placeholder: "Url to pdf" %>
          <div class="actions">
            <%= f.button :submit, class: "btn btn-primary" %>
            <%= link_to 'Back', :back, class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class='row'>
  <div class='col-md-2 sidebar'>
    <h3>Filters</h3>
    <ul class="nav nav-stacked">
      <li><a href='#'>Another Link 1</a></li>
      <li><a href='#'>Another Link 2</a></li>
      <li><a href='#'>Another Link 3</a></li>
    </ul>
  </div>
  <div class='col-md-10 products'>
    <div class="row">
      <h3>Products</h3>
    </div>
    <div class="row text-center">
      <% @products.each do |product| %>
        <div class="col-md-4 col-sm-4 feature">
          <div class="thumbnail">
            <img src="http://placehold.it/800x500" alt="">
            <div class="caption">
              <h3><%= product.title %></h3>
              <p><%= product.description %></p>
              <p>
                <%= link_to 'More Info', product, class: 'btn btn-default' %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="col-md-8">
        <img src="http://placehold.it/800x500" class="img-responsive" />
      </div>
      <div class="col-md-4">
        <h3 class="product-title"><%= @product.title %></h3>
        <p class="product-description"><%= @product.description %></p>
        <h4 class="price">Price: <span><%= number_to_currency(@product.price) %></span></h4>
        <div class="actions">
          <%= form_tag buy_path(id: @product.id) do %>
            <script src="https://checkout.stripe.com/v2/checkout.js"
              class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="<%= @product.title %>"
              data-amount="<%= (@product.price * 100).to_i %>"></script>
              <%= link_to 'Back', :back, class: "btn btn-default" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/transactions/pickup.html.erb
<h1>Download <%= @product.title %></h1>
<p>Thanks for buying "<%= @product.title %>". Here is your download url.</p>
<p><%= link_to "Download", download_url(guid: @sale.guid), target: :blank %></p>